GeoIP2 extension to sourcemod
alliedmodders/sourcemod pull request #1245
Opened 2020-04-26 05:46 UTC by Accelerator74

I updated the geoip extension for sourcemod using my geoip2 extension.

2020-10-02 23:47 UTC, KyleSanderson commented
@Accelerator74 can you resolve the merge conflicts.
@psychonic do you know the latest on this stuff? I know it's been a minute since we looked at this stuff but you're way more present with the maxmind stuff than I am.

2021-01-18 12:08 UTC, Accelerator74 commented
Added automatic search for the database file, because the mmdb format is also used by [DB-IP](https://db-ip.com/db) (so that you don't have to rename database files).

2021-03-08 02:47 UTC, KyleSanderson commented
@peace-maker this looks okay to me but I haven't looked at the upstream source. WDYT?

2021-03-10 23:32 UTC, peace-maker requested changes
This is cool stuff! Some comments inline.

Also is there an actual use case to supply the desired output language as a string like `"en"` to the natives?
I only see it being used to translate the country or whatever to a client's language to display it nicely. So you would always do. 
```
char sClientLang[8];
GetLanguageInfo(GetClientLanguage(client), sClientLang, sizeof(sClientLang), "", 0);
GeoipCountryEx(ip, ..., sClientLang);
```

Why not pass the target client index instead and lookup the client's language directly in the extension?

2021-03-10 23:32 UTC, peace-maker commented on extensions/geoip/extension.cpp
> +	const char *path[] = {"country", "names", lang, NULL};
How does libmaxminddb handle path lookups of invalid languages? Does it fall back to "en" on it's own?

If it just doesn't return anything for invalid languages, this should check if the supplied language is supported in the `metadata.languages` array and fall back to "en" if it's not.
The same needs to be done for all other natives supporting that language parameter.

2021-03-10 23:32 UTC, peace-maker commented on .gitmodules
> -[submodule "public/amtl"]
No need to touch this file.

2021-03-10 23:32 UTC, peace-maker commented on extensions/geoip/extension.cpp
> +	pCtx->StringToLocal(params[2], params[3], ccode);
StringToLocalUTF8

Same applies to all other natives.

2021-03-10 23:32 UTC, peace-maker commented on extensions/geoip/extension.cpp
> +	if (strlen(lang) == 0) strcpy(lang, "en");
It's not allowed to write to data returned by `LocalToString`. This can cause a buffer overflow in the VM.

2021-03-10 23:32 UTC, peace-maker commented on plugins/include/geoip.inc
> + * @param lang			Which language to the output of result the geoip2 lookup.
How about: `The desired language of the output as a language code.`
Same for all other natives with that parameter.

2021-03-11 06:44 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	const char *path[] = {"country", "names", lang, NULL};
Returns emptiness. In the native, there is a check for an empty result :)

For example:
```
#include <geoip>

public OnPluginStart()
{
	char temp[64];
	if (GeoipCountry("8.8.8.8", temp, sizeof(temp), "ch"))
	{
		PrintToServer("true %s", temp);
	}
	else
	{
		PrintToServer("false %s", temp);
	}
}
```
Result `false`

Is it still worth checking languages?)

2021-03-11 06:53 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	char buf[64];
This simply cannot be if the database was able to load)

The buffer should be sufficient.

The maxmind database contains: `de en es fr ja pt-BR ru zh-CN` (buffer size 29 characters)
In DBIP: `en de es fr ja pt-BR ru zh-CN fa ko` (buffer size 35 characters)

2021-03-11 07:04 UTC, Accelerator74 commented on .gitmodules
> -[submodule "public/amtl"]
This came from the geoip2-wip branch, from psychonic, when the libmaxminddb library was loaded there.

2021-03-11 07:11 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	if (strlen(lang) == 0) strcpy(lang, "en");
I don't quite understand what kind of fix is needed here :)

2021-03-11 07:14 UTC, Accelerator74 commented
> Why not pass the target client index instead and lookup the client's language directly in the extension?

For example, I don’t want some countries to be displayed in the player’s language and I want to choose which one language to display a message about geo data by IP address.

2021-03-11 09:28 UTC, peace-maker commented on extensions/geoip/extension.cpp
> +	char buf[64];
The [docs ](http://maxmind.github.io/libmaxminddb/index.html) say

> There is no requirement that the database metadata include languages or descriptions, so the count for these parts of the metadata can be zero. All of the other MMDB_metadata_s fields should be populated.

So we should handle that case for the future.

Cool, the buffer size is fine I guess 👍

2021-03-11 09:33 UTC, peace-maker commented on plugins/include/geoip.inc
> +native float GeoipDistance(float lat1, float lon1, float lat2, float lon2, system = SYSTEM_METRIC);
Whops, `system` needs a type here.

2021-03-11 09:52 UTC, peace-maker commented on extensions/geoip/extension.cpp
> +	const char *path[] = {"country", "names", lang, NULL};
Hm, I see. Is this the most intuitive and useful behavior though? Most likely you really want to display/store the data when you use one of the Geoip* natives, so if lookup for a language fails, you'd have to manually fall back to some other language. Every plugin would have to implement that logic, so wouldn't it be useful to do it straight in the natives to save some typing?

Instead of checking metadata.languages, which apparently might be empty, we could just see if the result is empty and try again with the server's language. This would mimic the fallback behavior of the general translation system in SourceMod. `Desired language -> server language -> english`

2021-03-11 10:00 UTC, peace-maker commented on extensions/geoip/extension.cpp
> +	if (strlen(lang) == 0) strcpy(lang, "en");
Hm, since the natives have a default value of `"en"` already, maybe just removing that line is enough? Together with the fallback to the server language, this'll behave the same.

2021-03-11 11:17 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	const char *path[] = {"country", "names", lang, NULL};
Nevertheless, it seems to me it will be strange if the plugin tries, for example, to find a country name on Japanese language, which is not in the database, and instead of an empty result it will display information in English. For me this is not logical)

The main task of the extension is, after all, the definition of geo data, and the choice of language, it seems to me, is only an additional option. Whether to use it or not, everyone must decide. The functionality of the sourcemod allows to determine the language of the player and who needs it, he will use it.

English remains the nationwide language, in which we actually display information by default :)

2021-03-11 13:56 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	const char *path[] = {"country", "names", lang, NULL};
>Instead of checking metadata.languages, which apparently might be empty, we could just see if the result is empty and try again with the server's language.

Besides, if we check not by the array of languages (`mmdb.metadata.languages.names`), we will have to access the database 2 more times (if suddenly the server language is also not found in the database). Yes, this is not essential, but why complicate the code so much? :)

2021-03-11 14:17 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	char buf[64];
Well, so far I have never seen in 2 years that the list of languages is not displayed :)

2021-03-12 06:45 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	const char *path[] = {"country", "names", lang, NULL};
Ok, i added language check :)

2021-03-12 10:35 UTC, peace-maker commented
Thank you! The fallback to the server language looks good.

I'll wait for a comment from other maintainers about the `const char[] lang` vs. `int client` parameter question to determine which language to use as proposed in my previous comment. Deliberately choosing a different language than the player's selected one to display a message to them sounds like a very "niche" use case. And you could still use `SetClientLanguage` briefly to force it to something else..

2021-03-12 10:48 UTC, Accelerator74 commented
Keep in mind that there are already some plugins that use this natives, because the geoip2 extension was released in 2018 :) But we can just add additional natives that will require the `client index`, not `char [] lang`.

2021-03-12 17:00 UTC, Accelerator74 commented
Nevertheless, I made the definition of the language by the client index :) I see colleagues from the amxmodx team did the same :)

P.S.: By the way, yes, most of the code was borrowed from them, but it seems that everything is one team :)

2021-05-20 23:09 UTC, KyleSanderson commented
@peace-maker do you need anything from me to help move this one forward?

2021-05-21 12:16 UTC, peace-maker commented
@KyleSanderson No, this looks good. I didn't notice the changes after my last comment, so this is fine now from my side. If you don't have any strong feelings towards selecting the country language by string, 🚢 
There are a couple of nits left like using `.c_str()` and then calculating the length again using `strlen()` while we could just use the length of the `std::string` and indentation issues in the include doc comments.

But above all this requires changes to the packaging scripts, since we can't ship the old `GeoIp.dat` with this anymore. We can't include the latest database either due to licensing requirements as you know. We can merge this and do a follow up to fix the packaging and documentation afterwards though, since that's not something Accelerator74 can do.

2021-05-21 12:20 UTC, peace-maker approved these changes

2021-05-21 12:20 UTC, peace-maker commented on plugins/include/geoip.inc
> + * @return				True on success, false otherwise.
Please use spaces instead of tabs for text alignment. Same for all documentation in this file!

2021-05-21 12:20 UTC, peace-maker commented on extensions/geoip/extension.cpp
> +	return (strlen(ccode) != 0) ? 1 : 0;
No need to call `strlen`, since we can just use `str.length()`. This pattern appears in nearly all other native callbacks as well.

2021-05-21 15:25 UTC, Accelerator74 commented on extensions/geoip/extension.cpp
> +	return (strlen(ccode) != 0) ? 1 : 0;
Hopefully ok now) I left `strlen` for RegionCode only. It's just that this function contains "hard" code :octocat:

2021-06-30 11:01 UTC, merged