Improvements on !admin menu flags
alliedmodders/sourcemod pull request #1364
Opened 2020-10-11 12:01 UTC by menesakdeniz

Lets say we have override the sm_unmute command and changed it to ADMFLAG_CUSTOM1.
Then create an admin, we gived our admin ADMFLAG_Chat flag, admin can't use sm_unmute command cause it doesnt have access to this command.
But if admin go into "!admin" menu then, he will able to run sm_unmute on "player command" menus

this vulnerability also affects mute,gag and silence commands

2020-10-19 17:28 UTC, peace-maker commented
Nice catch. I'm not sure if showing the disabled options is useful though. You should just not add the menu option at all if the user doesn't have access to it.

2020-10-19 18:07 UTC, menesakdeniz commented
i made this way because if the admin wants to see if user gagged or not. It can be changed easily

2020-10-19 18:28 UTC, peace-maker commented
Seeing who is muted is part of the permission in my opinion. If you can't use sm_mute you shouldn't see anything about it anywhere.

2020-10-20 16:47 UTC, menesakdeniz commented
Well, I changed it according to your opinion

2020-10-23 11:52 UTC, peace-maker requested changes
Thank you, this looks good except for the nits! 👍

2020-10-23 11:52 UTC, peace-maker commented on plugins/basecomm/gag.sp
> +	menu.AddItem(opt, buffer, ITEMDRAW_DEFAULT);
That change isn't necessary anymore

2020-10-23 11:52 UTC, peace-maker commented on plugins/basecomm/gag.sp
> +
Spurious whitespace changes

2020-10-23 23:30 UTC, menesakdeniz commented on plugins/basecomm/gag.sp
> +
this line is deleted

2020-10-23 23:31 UTC, menesakdeniz commented on plugins/basecomm/gag.sp
> +	menu.AddItem(opt, buffer, ITEMDRAW_DEFAULT);
deleted unnecessary argument

2020-10-24 17:22 UTC, merged

2020-10-24 17:22 UTC, peace-maker commented
Thank you!

2020-10-24 18:49 UTC, psychonic commented
Was this already fixed in master? (I don’t have a PC handy but saw merged to 1.10-dev)

Sent from my iPhone

> On Oct 24, 2020, at 1:22 PM, peace-maker <notifications@github.com> wrote:
> 
> ﻿
> Thank you!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.