Update cookie funcs to return Cookie methodmap
alliedmodders/sourcemod pull request #1379
Opened 2020-10-30 19:38 UTC by JoinedSenses

Just like the behavior of functions like CreateArray which return ArrayList, cookie functions should return Cookie.

2020-11-05 09:54 UTC, peace-maker requested changes
Since the keyword is lowercase, documenting it as `Null` might confuse users when they copy it from the docs? `INVALID_HANDLE` had unambiguous casing before 😄

2020-11-05 09:54 UTC, peace-maker commented on plugins/include/clientprefs.inc
> +	// @return              A handle to the cookie if it is found. Null otherwise.
```suggestion
	// @return              A handle to the cookie if it is found, null otherwise.

```

2020-11-05 09:54 UTC, peace-maker commented on plugins/include/clientprefs.inc
> + * @return              A handle to the cookie if it is found. Null otherwise.
```suggestion
 * @return              A handle to the cookie if it is found, null otherwise.

```

2020-11-05 12:32 UTC, JoinedSenses commented
> Since the keyword is lowercase, documenting it as `Null` might confuse users when they copy it from the docs? `INVALID_HANDLE` had unambiguous casing before 😄

¯\_(ツ)_/¯

2020-11-05 13:01 UTC, peace-maker approved these changes
Thanks!

2020-11-07 21:15 UTC, Headline approved these changes
Looks great, thanks!

2020-11-07 21:16 UTC, merged