Execute ConVarQueryFinished if client disconnects
alliedmodders/sourcemod pull request #1384
Opened 2020-11-26 00:23 UTC by Deathreus

So people passing handles to the extra data can close them, adds a new return value to check if this happened

2020-11-26 15:04 UTC, asherkin reviewed
This all looks sane to me. I'll leave it open for a bit in case any one else has any comments on the use of `-1` (I saw a bit on Discord this morning.) I think the only real risk here is SMAC's convar checks, so as long as that's not going to start banning people when getting the value here I'm happy!

2020-11-26 15:04 UTC, asherkin commented on core/ConVarManager.cpp
> +				pCallback->PushString("\0");
Any reason for the double-nul in these strings here?

```suggestion
				pCallback->PushString("");
				pCallback->PushString("");
```

2020-11-26 16:37 UTC, psychonic commented
It might be worth exposing a feature capability so that plugins that want or need to require this can know if it would ever be called.

2020-11-26 17:12 UTC, Deathreus commented on core/ConVarManager.cpp
> +				pCallback->PushString("\0");
No particular reason, just thought it was a convention, I'll change it

2020-11-26 23:47 UTC, KyleSanderson requested changes
This doesn't feel quite right - see comments please.

2020-11-26 23:47 UTC, KyleSanderson commented on core/ConVarManager.cpp
> +				pCallback->PushCell(eQueryCvarValueStatus_Cancelled);
This should be QUERYCOOKIE_FAILED equivalent. The Client is already disconnected, and the query failed.

2020-11-26 23:47 UTC, KyleSanderson commented on core/ConVarManager.cpp
> +				pCallback->PushCell(InvalidQueryCvarCookie);
This feels broken. QUERYCOOKIE_FAILED is 0 and InvalidQueryCvarCookie is -1.

2020-11-26 23:47 UTC, KyleSanderson commented on core/ConVarManager.cpp
> +	IPluginFunction *pCallback = NULL;
This should be in the loop - we're not using the post-result in this scope.

2020-11-26 23:52 UTC, asherkin commented on core/ConVarManager.cpp
> +				pCallback->PushCell(eQueryCvarValueStatus_Cancelled);
The naming here was discussed before the PR was made, `_Cancelled` was preferred as there was no failure, and it lets us extend this result to the other cancellation cases in the future (such as the plugin unloading) if desired.

2020-12-01 02:21 UTC, Deathreus commented on core/ConVarManager.cpp
> +	IPluginFunction *pCallback = NULL;
You right

2020-12-01 02:32 UTC, Deathreus commented on core/ConVarManager.cpp
> +				pCallback->PushCell(eQueryCvarValueStatus_Cancelled);
The value is the number it is due to this reusing a SDK enum for the values, and the name makes more sense in context and lines up to said enum

2020-12-01 15:39 UTC, peace-maker commented on plugins/include/convars.inc
> +	ConVarQuery_Cancelled = -1,			//< Client disconnected during query */
The other comments used spaces for alignment instead of tabs.

2021-01-30 19:03 UTC, peace-maker commented
What happened here?

2021-02-01 21:58 UTC, Deathreus commented
> What happened here?

Oopsie, pulled into here on accident, let me see if I can clean it up

2021-03-08 02:20 UTC, KyleSanderson requested changes
I agree we should handle this case, but the only avenue the client (readas: script caller) has to reconcile this is to stay on the QueryCookie. When we return 0 that still leaves the initial issue present when there's multiple inflight cases. It's like you're in prison, have two people with the name Wyatt, and get two callbacks for Wyatt but don't know who's clothes are who. You can certainly guess, but you're going to be wrong half the time (and more with the more callbacks outstanding).

2021-03-08 02:20 UTC, KyleSanderson commented on core/ConVarManager.cpp
> +				pCallback->PushCell(0);
Where's this value?

2021-03-08 12:42 UTC, asherkin commented on core/ConVarManager.cpp
> +				pCallback->PushCell(0);
Good catch, it looks like it should be available as `query.cookie`.

2021-03-09 20:10 UTC, Deathreus commented on core/ConVarManager.cpp
> +				pCallback->PushCell(0);
This is a good point, but I'm not sure how the cookie is needed? I added the value but a more clear explanation rather than an analogy would be appreciated, thanks

2021-03-15 10:01 UTC, peace-maker approved these changes

2021-03-15 19:43 UTC, KyleSanderson approved these changes

2021-03-15 19:44 UTC, merged