Switch to the new CommandIterator() methodmap
alliedmodders/sourcemod pull request #1388
Opened 2020-11-28 12:03 UTC by iNilo

`ReadCommandIterator` 
->
```
CmdIter.GetName(Name, sizeof(Name));
Flags = CmdIter.Flags;
CmdIter.GetDescription(Desc, sizeof(Desc));
```

2020-11-29 15:23 UTC, peace-maker requested changes
Thanks for the cleanup! A few things inline.

2020-11-29 15:23 UTC, peace-maker commented on plugins/adminhelp.sp
> +			if(CheckCommandAccess(client, Name, Flags))
This check prevents the next page from showing up based on if the first item on the next page isn't available to the user. There might be more commands that are available, so the check should stay gone.

2020-11-29 15:23 UTC, peace-maker commented on plugins/adminhelp.sp
> +			Flags = CmdIter.Flags;
You can get rid of the `Flags` variable and use `CmdIter.Flags` directly.

2021-03-07 14:41 UTC, peace-maker commented on plugins/adminhelp.sp
>  			CmdIter.GetName(Name, sizeof(Name));
This doesn't appear to be necessary anymore.

2021-03-08 01:58 UTC, KyleSanderson requested changes
This should respect COMMANDS_PER_PAGE on help. This isn't on you, but there's existing tech debt here that we can hopefully improve.

2021-03-08 01:58 UTC, KyleSanderson commented on plugins/adminhelp.sp
>  		int i = 1;
@peace-maker do all of our command indexes start at 1? These aren't cookies or actual indicies, but what the client can see.

2021-03-08 01:58 UTC, KyleSanderson commented on plugins/adminhelp.sp
>  		int i = 1;
This should also respect COMMANDS_PER_PAGE.

2021-05-20 23:05 UTC, KyleSanderson commented
@iNilo is there anything we can do to help you with moving this one forward?

2022-01-03 14:05 UTC, peace-maker commented on plugins/adminhelp.sp
>  		int i = 1;
It think that index is just for display and fine to start at 1 since it's not used anywhere.
Paginating the `sm_search` output would require changes to the translation files and seems out of scope for this PR.

2022-01-03 14:13 UTC, peace-maker approved these changes

2022-02-01 17:58 UTC, KyleSanderson approved these changes

2022-02-01 18:13 UTC, merged