Add new trie native: ExistInTrie()
alliedmodders/sourcemod pull request #1390
Opened 2020-11-29 01:22 UTC by Einyux

Nothing fancy here, just a new native to check if a key exists in a trie.
It helps to avoid to create a dummy variable when using GetTrieXXX() to check a key existence.

Native name can be changed if it's not to your liking :-D.

2020-11-29 01:25 UTC, Headline requested changes
Just a few nits, otherwise I'm okay with taking this.

2020-11-29 01:25 UTC, Headline commented on core/logic/smn_adt_trie.cpp
> +	{"ExistInTrie",				ExistInTrie},
Feel free to remove this binding - old syntax can stay in the past

2020-11-29 01:25 UTC, Headline commented on plugins/include/adt_trie.inc
> +native bool ExistInTrie(Handle map, const char[] key);
ditto

2020-11-29 01:25 UTC, Headline commented on plugins/include/adt_trie.inc
> +	public native bool Exist(const char[] key);
I think `HasKey` is a better name that is easier to understand

2020-11-29 01:31 UTC, Einyux commented on core/logic/smn_adt_trie.cpp
> +	{"ExistInTrie",				ExistInTrie},
Ok, I will remove it.

2020-11-29 01:31 UTC, Einyux commented on plugins/include/adt_trie.inc
> +native bool ExistInTrie(Handle map, const char[] key);
Same

2020-11-29 01:39 UTC, Einyux commented on plugins/include/adt_trie.inc
> +	public native bool Exist(const char[] key);
Browsing though Internet I found some other names:

public native bool Contain(const char[] key); // From C++ 20
public native bool ContainKey(const char[] key); // From Java

2020-11-29 02:20 UTC, Einyux commented on plugins/include/adt_trie.inc
> +	public native bool Exist(const char[] key);
For the moment, I updated it to "ContainsKey", similar to C#.
https://docs.microsoft.com/en-gb/dotnet/api/system.collections.generic.idictionary-2.containskey?view=net-5.0

2020-11-30 02:24 UTC, Headline approved these changes

2020-11-30 10:08 UTC, asherkin approved these changes
LGTM, thanks - could bikeshed the name forever but I think `ContainsKey` is nice and clear.

2020-12-01 04:51 UTC, merged