Add sm_dump_datamaps_xml
alliedmodders/sourcemod pull request #1409
Opened 2020-12-20 04:08 UTC by Scags

There's an `sm_dump_netprops_xml` but not an `sm_dump_datamaps_xml` and since I went a bit nuts parsing a plain text file, I thought it would be useful to extend it into a parsable format.

This also adds the element offset for sub-class tables since I needed them for my exact purpose.

2021-03-07 12:57 UTC, Headline commented on extensions/sdktools/vhelpers.cpp
> +		META_CONPRINT("Usage: sm_dump_datamaps <file>\n");
sm_dump_datamaps_xml here

2021-03-07 12:59 UTC, Headline requested changes
Looks good!

Just that one tiny bit I believe

2021-03-07 12:59 UTC, Headline commented on extensions/sdktools/vhelpers.cpp
> +		META_CONPRINT("Usage: sm_dump_datamaps <file>\n");
sm_dump_datamaps_xml here

2021-03-08 19:58 UTC, Scags commented on extensions/sdktools/vhelpers.cpp
> +		META_CONPRINT("Usage: sm_dump_datamaps <file>\n");
Gotcha, funny how I managed to catch that on the other print 🙃.

2021-03-08 22:27 UTC, Headline approved these changes

2021-03-08 22:28 UTC, merged