Expose SourcePawn JIT metadata config
alliedmodders/sourcemod pull request #1412
Opened 2020-12-27 18:25 UTC by asherkin

Adds a new option to core.cfg to configure the debug/profiling metadata written by the JIT.

Depends on alliedmodders/sourcepawn#533.

2021-03-07 23:32 UTC, KyleSanderson reviewed
Style is all over the map on this one if you can tighten it up a bit.

2021-06-30 19:55 UTC, peace-maker requested changes
Is it fine to change the flags during runtime using `sm config JITMetadata jitdump`?

2021-06-30 19:55 UTC, peace-maker commented on core/sourcemod.cpp
> +			return ConfigResult_Reject;
Would be nice to put the allowed values into the `error` message here.

2021-06-30 20:16 UTC, asherkin commented
> Is it fine to change the flags during runtime using `sm config JITMetadata jitdump`?

It isn't going to cause any harm, but it may or may not have any effect depending on the current state of things.

2021-06-30 21:37 UTC, peace-maker approved these changes

2021-06-30 22:20 UTC, merged