fix issues when loading randomcycle from disabled folder
alliedmodders/sourcemod pull request #1428
Opened 2021-02-12 23:30 UTC by sapphonie

currently, when loading randomcycle, it runs `Timer_RandomizeNextmap` twice, leading to odd behavior where the map gets changed twice after timelimit is reached. This fixes that issue by only allowing the timer to be run once per map.

2021-02-13 18:37 UTC, peace-maker commented
So `OnConfigsExecuted` is executed multiple times when a plugin is loaded late?

2021-03-07 22:50 UTC, KyleSanderson commented
> So `OnConfigsExecuted` is executed multiple times when a plugin is loaded late?

If the map changes twice from our data model there can be multiples of these timers running because this isn't killed with fire when the level ends. To fix this one I think we just need TIMER_FLAG_NOMAPCHANGE and nuke the global as it isn't needed and welcomes glitches.

There was an ancient issue with OnConfigsExecuted firing multiple times, and that could indeed be the issue here (if you want to step through with a debugger that would be cool). However, I'd suspect there's multiple map plugins loaded at the moment, so the server is changing levels twice (which also happened to me, over 10 years ago).

I do believe the current PR resolves the issue, but I don't believe it's the correct fix.

2021-03-12 16:35 UTC, peace-maker requested changes
Thank you for bringing this up! Please consider the following change if you have the time!

2021-03-12 16:35 UTC, peace-maker commented on plugins/randomcycle.sp
> -	CreateTimer(5.0, Timer_RandomizeNextmap); // Small delay to give Nextmap time to complete OnMapStart()
As KyleS pointed out, the cleaner fix for this issue is setting the `TIMER_FLAG_NO_MAPCHANGE` flag here instead of letting the timer run twice.

2021-03-13 20:25 UTC, sapphonie commented on plugins/randomcycle.sp
> -	CreateTimer(5.0, Timer_RandomizeNextmap); // Small delay to give Nextmap time to complete OnMapStart()
fixed(?)

2021-03-13 22:08 UTC, KyleSanderson requested changes
The flag is in the wrong arg.

2021-03-13 22:08 UTC, KyleSanderson commented on plugins/randomcycle.sp
> +	CreateTimer(5.0, Timer_RandomizeNextmap, TIMER_FLAG_NO_MAPCHANGE); // Small delay to give Nextmap time to complete OnMapStart()
This should be in the flags field, not the data field.

2021-03-14 03:22 UTC, sapphonie commented on plugins/randomcycle.sp
> +	CreateTimer(5.0, Timer_RandomizeNextmap, TIMER_FLAG_NO_MAPCHANGE); // Small delay to give Nextmap time to complete OnMapStart()
lmfao oops

2021-03-14 04:34 UTC, KyleSanderson approved these changes

2021-03-14 08:53 UTC, peace-maker approved these changes

2021-03-14 09:00 UTC, Headline approved these changes

2021-03-14 09:02 UTC, merged