Add ConVar.GetDescription() method
alliedmodders/sourcemod pull request #1449
Opened 2021-03-18 01:11 UTC by Wend4r

Issue #1432

2021-03-18 01:12 UTC, Wend4r commented
Works
![image](https://user-images.githubusercontent.com/47463683/111558603-1f9f9000-87a0-11eb-8ab8-7a8f3316a387.png)

2021-03-19 03:02 UTC, Headline approved these changes

2021-03-19 03:02 UTC, Headline commented on plugins/include/convars.inc
> +native void GetConVarDescription(Handle convar, char[] buffer, int maxlength);
I understand adding this for the sake of completion, but we don't add old style functions for new features. Rest looks good to me, though! 😄

2021-03-19 10:04 UTC, peace-maker commented
We need to figure out how to handle changes to translation phrases before merging this!

2021-03-19 10:11 UTC, Wend4r commented
> We need to figure out how to handle changes to translation phrases before merging this!
I followed the standards set by `basecommands`
https://github.com/alliedmodders/sourcemod/blob/ad485069a837f602bdeeeb50f9e02452b3860ecd/plugins/basecommands.sp#L65-L66
Phrases from ConVars are found in these 2 files.
I think this already needs to be fixed with a separate solution.

2021-03-19 10:20 UTC, peace-maker commented
Yes, sorry, this is nothing wrong with your changes. Just like #597 changes to the translation files have to be reflected in the [translator tool](https://sm.alliedmods.net/translator/) used to gather all the different languages. That update isn't automated yet and the [process of translation](https://wiki.alliedmods.net/Translating_SourceMod) hasn't been revisited since SourceMod switched to a rolling release cycle afaik.

2021-03-19 10:27 UTC, asherkin commented
I think it would be best to remove the basecommands changes so we can get the new API merged.

2021-03-20 16:36 UTC, peace-maker requested changes
The non-methodmap native needs to go, but otherwise this looks great!

2021-03-20 16:36 UTC, peace-maker commented on core/smn_console.cpp
> +	pContext->StringToLocalUTF8(params[2], params[3], pConVar->GetHelpText(), NULL);
Can `GetHelpText` ever return NULL?

2021-03-21 11:46 UTC, Wend4r commented on core/smn_console.cpp
> +	pContext->StringToLocalUTF8(params[2], params[3], pConVar->GetHelpText(), NULL);
It will return a pointer with an empty string if there is no description

2021-03-21 11:54 UTC, Wend4r commented on core/smn_console.cpp
> +	pContext->StringToLocalUTF8(params[2], params[3], pConVar->GetHelpText(), NULL);
https://github.com/alliedmodders/hl2sdk/blob/csgo/tier1/convar.cpp#L163

2021-03-21 12:14 UTC, Wend4r commented
When there was an active change with `basecommands` it returns an empty string aka NULL_STRING from `ConVar.GetDescription()` from ConVars without a description.

2021-03-21 14:08 UTC, peace-maker commented on core/smn_console.cpp
> +	pContext->StringToLocalUTF8(params[2], params[3], pConVar->GetHelpText(), NULL);
Cool, let's assume this is the case for all games and sdks

2021-03-21 14:09 UTC, peace-maker approved these changes

2021-03-21 14:10 UTC, peace-maker commented
`NULL_STRING` and an empty string aren't the same, but I guess you're talking about an empty string, so this is fine.

2021-03-21 14:10 UTC, merged