Add HookPluginUnload() and UnhookPluginUnload() functions
alliedmodders/sourcemod pull request #1462
Opened 2021-04-03 13:04 UTC by Wend4r

Issue #890 

I wrote this Pull Request in considerations of the handles principles that a plugin must necessarily know when the handle closes or close manually if it is cloned.

2021-04-03 13:08 UTC, Wend4r commented
Code to check

`pull1462.sp`
```c
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

#define MAX_Cycle_MESSAGE_LENGTH 1024

enum struct CycleMessageInfo
{
	Handle plugin;
	char message[MAX_Cycle_MESSAGE_LENGTH];

	void SendMessage()
	{
		PrintToServer("%s", this.message);
	}
}

ArrayList g_CycleMessageList;

public APLRes AskPluginLoad2(Handle myself, bool late, char[] error, int err_max)
{
	CreateNative("SendCycleMessage", Native_SendCycleMessage);
}

any Native_SendCycleMessage(Handle plugin, int numParams)
{
	CycleMessageInfo info;

	info.plugin = plugin;

	LogMessage("Detected %X plugin", plugin);

	GetNativeString(1, info.message, sizeof(CycleMessageInfo::message));
	g_CycleMessageList.PushArray(info);

	HookPluginUnload(plugin, OnPluginUnloaded);
}

public void OnPluginStart()
{
	g_CycleMessageList = new ArrayList(sizeof(CycleMessageInfo));

	CreateTimer(5.0, OnPrintMessageTimer, _, TIMER_REPEAT);
}

Action OnPrintMessageTimer(Handle timer)
{
	CycleMessageInfo info;

	for(int i = 0, length = g_CycleMessageList.Length; i != length; i++)
	{
		g_CycleMessageList.GetArray(i, info, sizeof(info));
		info.SendMessage();
	}
}

void OnPluginUnloaded(Handle plugin)
{
	LogMessage("Plugin %X is unloaded", plugin);

	int index = g_CycleMessageList.FindValue(plugin, CycleMessageInfo::plugin);

	g_CycleMessageList.Erase(index);
}
```

`pull1462_module.sp`
```c
#pragma semicolon 1
#pragma newdecls required

#include <sourcemod>

native void SendCycleMessage(const char[] message);

public void OnPluginStart()
{
	SendCycleMessage("Hello!");
}
```

Result:
![image](https://user-images.githubusercontent.com/47463683/113479258-ad64c600-9496-11eb-8e34-3ef6b5a7f895.png)

2021-05-20 22:53 UTC, KyleSanderson commented
@dvander we've been all over the map on this one over the years - what's your take? I need it for memory management in another plugin but that usecase is very different.

2021-05-24 18:29 UTC, dvander requested changes
The idea behind this seems good to me, but there are some complexity and stability issues here.

I think you could fix them by removing PluginUnloadHookInfo. If you put the IChangeableForward directly on the CPlugin object, this patch becomes a lot simpler, and you won't have the stability issues (IChangeableForward handles the complexity of list iteration for you).

2021-05-24 18:29 UTC, dvander commented on plugins/include/sourcemod.inc
> +native bool UnhookPluginUnload(Handle plugin, PluginUnloaded callback);
Do you need the Unhook method? The unload event only happens once per plugin. With a use case like yours, either the controller plugin unloads (and no longer cares about removing the hook), or the target plugin unloads, and the hook fires.

The scenarios where you really care about removing the hook are pretty limited, and it would simplify this change quite a bit.

2021-05-24 18:29 UTC, dvander commented on core/logic/PluginSys.h
> +	bool UnhookPluginUnload(IPlugin *pPluginToUnhook, IPluginFunction *pHookFunction);
No need for spaces between these methods.

2021-05-24 18:29 UTC, dvander commented on core/logic/PluginSys.cpp
> +			pForwardToCall = iter->pForward;
Move the declaration above to here, eg:

    IChangeableForward *pForwardToCall = iter->pForward;

2021-05-24 18:29 UTC, dvander commented on core/logic/PluginSys.cpp
> +			m_PluginUnloadHooks.erase(iter);
Calling [Unh|H]ookPluginUnload in this callback will crash.

2021-05-24 19:24 UTC, Wend4r commented on plugins/include/sourcemod.inc
> +native bool UnhookPluginUnload(Handle plugin, PluginUnloaded callback);
The plugin can call natives, which can be execute unhook.
Similar to the concept of allocate an object and closing it.

2021-05-24 19:34 UTC, dvander commented on plugins/include/sourcemod.inc
> +native bool UnhookPluginUnload(Handle plugin, PluginUnloaded callback);
Does it matter, though? A global forward - something like - "OnNotifyPluginUnloaded" - would be very simple to implement and would require only a bit of filtering on your end. And if you can do that filtering, you don't need the Unhook method.

2021-05-24 20:34 UTC, Wend4r commented
Works!

[source.zip](https://github.com/alliedmodders/sourcemod/files/6534833/source.zip)
```
sm plugins unload pull1462
[SM] Plugin pull1462.smx unloaded successfully.
sm plugins load pull1462
[SM] Loaded plugin pull1462.smx successfully.
sm plugins load pull1462_module
L 05/24/2021 - 23:31:18: [pull1462.smx] Detected 27800CC plugin
[SM] Loaded plugin pull1462_module.smx successfully.
Hello!
Hello!
Hello!
sm plugins unload pull1462_module
L 05/24/2021 - 23:31:34: [pull1462.smx] Destroyed 27800CC plugin
[SM] Plugin pull1462_module.smx unloaded successfully.
```

2021-05-24 20:44 UTC, dvander requested changes
Thanks! This is *much* simpler. Just one small comment.

2021-05-24 20:44 UTC, dvander commented on core/logic/PluginSys.cpp
> +	m_pOnNotifyPluginUnloaded->Execute(NULL);
Can you move this to above line 1502 (eg before OnPluginUnloaded callbacks fire?) That ordering will be a tiny bit safer.

Once "OnPluginUnloaded" has been called, we don't want any new stuff getting accidentally registered on the plugin, since otherwise it might leak or crash.

2021-05-24 20:55 UTC, KyleSanderson commented
This looks slightly bugged (the forward says Unloaded, but the plugin is still loaded). I think we may need two forwards here, one for OnPluginUnloading, and a final for OnPluginUnloaded after everything has released resources.

2021-05-24 21:00 UTC, dvander approved these changes

2021-05-24 21:02 UTC, dvander commented
I think this is fine and we can merge it.

Once "OnPluginEnd" has been called, it is for all intents and purposes unloaded, and the only thing left to do is cleanup. Besides not having a clear use case, what you're asking for has a catch-22: if you release the resources, you don't have the handle anymore, so how can you notify?

2021-05-24 21:14 UTC, KyleSanderson commented
> Once "OnPluginEnd" has been called, it is for all intents and purposes unloaded, and the only thing left to do is cleanup. 

For my specific usecase Forwards are destroyed in OnPluginUnloaded, so we need a final call for OnPluginDestroyed (or the equivalent of it) in pawn. Wendr is looking for the same behaviour it looks like here, because they're using the plugin handle as a value to be found in an array. When you'd use OnPluginUnloading is if you need the pubinfo from the plugin, or to access resources still allocated which would match the OnClientDisconnecting vs OnClientDisconnected behaviour, no?

2021-05-24 21:15 UTC, Wend4r commented
> This looks slightly bugged (the forward says Unloaded, but the plugin is still loaded). I think we may need two forwards here, one for OnPluginUnloading, and a final for OnPluginUnloaded after everything has released resources.

In my case, this forward is needed to clean up the data attaches to the native calling handler at the SourcePawn level. I do not know in which cases an additional forward for a fully cleaned plugin from extensions.

2021-05-24 21:30 UTC, dvander commented
"For my specific usecase Forwards are destroyed in OnPluginUnloaded" - This doesn't explain why such a thing would be needed, and indeed there is nothing within SourceMod that needs this distinction internally.

2021-05-24 21:30 UTC, merged

2021-05-24 22:08 UTC, KyleSanderson commented
Thanks for bearing with us team, this has now landed (if there are other issues related to this please let them know).

https://github.com/alliedmodders/sourcemod/pull/948
https://github.com/alliedmodders/sourcemod/issues/1482
https://github.com/alliedmodders/sourcemod/issues/1481

2021-05-24 23:22 UTC, dragokas commented
That commit does not cover OnPluginLoad(), which is now closed: https://github.com/alliedmodders/sourcemod/issues/1482