[Untested] New cvar to exclude spectators in rock the vote
alliedmodders/sourcemod pull request #1474
Opened 2021-04-15 13:31 UTC by eyal282

Me and a lot of server owners use spectator team as a place to be afk for a bit. Spectators that are afk clog rtv as they aren't truly in the server.

This PR allows server owners to prevent spectators from clogging it up.

2021-04-18 22:59 UTC, KyleSanderson requested changes
Can you test this?

2021-04-19 14:28 UTC, eyal282 commented
> Can you test this?

Not the easiest thing for me but I will see.

2022-02-01 18:07 UTC, peace-maker requested changes
I've added some comments. Do you still plan to work on this feature?

2022-02-01 18:07 UTC, peace-maker commented on plugins/rockthevote.sp
> +		if(g_Voted[client])
This looks like some duplicated code from `OnClientDisconnect`. Might be worth to wrap this in a helper function.

2022-02-01 18:07 UTC, peace-maker commented on plugins/rockthevote.sp
> +	if(team == 1)
You probably want to use your `g_iSpectatorTeam` variable here.

2022-02-01 18:11 UTC, peace-maker commented
Also in some games players might end up in the "unassigned" team with index 0 if they never select a team after connect, but are effectively spectating. So maybe we want to change the `IsClientSpectatorTeam` to do `<= specteamindex`?

Are we sure every game uses the `player_team` event?

2022-02-03 20:48 UTC, eyal282 commented
Sorry but it's been almost a year. Recycle my PR if you want.

2022-02-03 20:48 UTC, closed without merging

2022-02-03 23:02 UTC, peace-maker commented
Aw, sorry for the late review. I was waiting for you to test your draft.