Added `@error` documentation for every function that's missing it.
alliedmodders/sourcemod pull request #1498
Opened 2021-06-11 10:52 UTC by Natanel-Shitrit

2021-06-20 12:16 UTC, Natanel-Shitrit commented
This is all i was able to find 😄
[AlliedModders Code Search](cs.alliedmods.net) was used for this, really helpful.

2021-06-20 19:52 UTC, dvander approved these changes

2021-06-21 11:24 UTC, asherkin requested changes
This all looks really good, left a smattering of inlines - mostly just style changes for consistency with the other changed messages.

I've only commented on one instance of each, so you'll need to check around not just use GitHub's inline suggestions.

2021-06-21 11:24 UTC, asherkin commented on plugins/include/sdkhooks.inc
> + * @error                Invalid entity, attacker, inflictor, weapon entity.
```suggestion
 * @error                Invalid entity, attacker, inflictor, or weapon entity.
```

2021-06-21 11:24 UTC, asherkin commented on plugins/include/sdktools.inc
> +native bool PrepSDKCall_SetFromConf(GameData gameconf, SDKFuncConfSource source, const char[] name);
It'd be good to change the docs for `gameconf` to reference `null` instead of `INVALID_HANDLE`.

2021-06-21 11:24 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid client index, client not in game or lack of mod support.
Most of the annotations use the oxford comma, but there are a couple here that don't - it'd be good to consistently use it.

2021-06-21 11:24 UTC, asherkin commented on plugins/include/sdktools_gamerules.inc
> + * @error               Not supported, prop type is not an integer or invalid entity.
```suggestion
 * @error               Prop type is not an entity, or lack of mod support.
```

`@return` says -1 will be returned if the entity is invalid.

2021-06-21 11:24 UTC, asherkin commented on plugins/include/sourcemod.inc
> + * @error               Address is null or it's pointing to a reserved memory, invalid NumberType.
```suggestion
 * @error               Address is null or pointing to reserved memory.
```
Wording change, and the compiler won't allow code to be compiled with an invalid NumberType without hackery, so there is no need to call that out.

2021-06-21 11:50 UTC, peace-maker commented on plugins/include/sdktools.inc
> +native bool PrepSDKCall_SetFromConf(GameData gameconf, SDKFuncConfSource source, const char[] name);
Such changes break backwards compatiblity with code not using the GameData methodmap, but the old api. Please leave the type as `Handle`! Changing return types of legacy api to some methodmap isn't a problem, but parameter type changes are bad.

2021-06-21 11:51 UTC, asherkin commented on plugins/include/sdktools.inc
> +native bool PrepSDKCall_SetFromConf(GameData gameconf, SDKFuncConfSource source, const char[] name);
I tested this change and it seemed fine with being given a `Handle` - I believe the compat issue only applies to changing forwards, not natives.

2021-06-21 12:48 UTC, Natanel-Shitrit commented on plugins/include/sdktools.inc
> +native bool PrepSDKCall_SetFromConf(GameData gameconf, SDKFuncConfSource source, const char[] name);
> Such changes break backwards compatiblity with code not using the GameData methodmap, but the old api. Please leave the type as `Handle`! Changing return types of legacy api to some methodmap isn't a problem, but parameter type changes are bad.

Reverted back to `Handle`, thanks for the heads up.

2021-06-21 16:14 UTC, Natanel-Shitrit commented on plugins/include/sdktools_gamerules.inc
> + * @error               Not supported, prop type is not an integer or invalid entity.
I was wondering about what do to with the `GameRules_SetPropEnt` function because it is checking if the entity is valid.
It'll unset if -1 is set but not any invalid entity ([and looks like it will throw a native error](https://cs.alliedmods.net/sourcemod/source/extensions/sdktools/gamerulesnatives.cpp#421))

2021-06-21 16:21 UTC, asherkin commented on plugins/include/sdktools_gamerules.inc
> + * @error               Not supported, prop type is not an integer or invalid entity.
Set should have it in `@error`, but this is Get :)

2021-06-21 16:27 UTC, Natanel-Shitrit commented on plugins/include/sdktools_gamerules.inc
> + * @error               Not supported, prop type is not an integer or invalid entity.
Yes i was just wondering about set because you said `I've only commented on one instance of each`, sorry for not mentioning it 😄

2021-06-24 14:31 UTC, asherkin approved these changes
Looking good - a handful of minor grammatical tweaks I'm gonna apply before merging, just doing it this way to use the web UI because I'm lazy.

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid client index, client not in game or lack of mod support.
```suggestion
 * @error               Invalid client index, client not in game, or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error                   Invalid edict index, no map is running or lack of mod support.
```suggestion
 * @error                   Invalid edict index, no map is running, or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid entity index, or lack of mod support.
```suggestion
 * @error               Invalid entity index or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid entity index, or lack of mod support.
```suggestion
 * @error               Invalid entity index or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid entity index, or lack of mod support.
```suggestion
 * @error               Invalid entity index or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid entity index, or lack of mod support.
```suggestion
 * @error               Invalid entity index or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid client index, client not connected or lack of mod support.
```suggestion
 * @error               Invalid client index, client not connected, or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @error               Invalid client index, client not connected or lack of mod support.
```suggestion
 * @error               Invalid client index, client not connected, or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_sound.inc
> + * @error               Invalid client index, client not in game or lack of mod support.
```suggestion
 * @error               Invalid client index, client not in game, or lack of mod support.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_trace.inc
> + * @error               Invalid entity
```suggestion
 * @error               Invalid entity.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_voice.inc
> + * @error               Invalid client index, or client not connected.
```suggestion
 * @error               Invalid client index or client not connected.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_voice.inc
> + * @error               Invalid client index, or client not connected.
```suggestion
 * @error               Invalid client index or client not connected.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_voice.inc
> + * @error               Invalid listener or sender client index, or not connected.
```suggestion
 * @error               Listener or sender client index is invalid or not connected.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_voice.inc
> + * @error               Invalid listener or sender client index, or not connected.
```suggestion
 * @error               Listener or sender client index is invalid or not connected.
```

2021-06-24 14:31 UTC, asherkin commented on plugins/include/sdktools_voice.inc
> + * @error               Invalid muted or mutee client index, or not connected.
```suggestion
 * @error               Muter or mutee client index is invalid or not connected.
```

2021-06-24 14:45 UTC, merged