Add StringToBigInt() and BigIntToString() natives
alliedmodders/sourcemod pull request #1511
Opened 2021-06-25 08:27 UTC by Wend4r

2021-06-25 08:38 UTC, Wend4r commented
I need this change to convert a big int array to a string value, working with unix bigstamp, SteamID64, EconItem itemid and etc.. 
For compatibility with these natives:
https://sourcemod.dev/#/sourcemod/function.GetTime
https://github.com/alliedmodders/sourcemod/blob/master/plugins/include/clients.inc#L320 by AuthId_SteamID64
https://github.com/komashchenko/PTaH/blob/master/PTaH.inc#L510
https://github.com/alliedmodders/sourcemod/blob/master/plugins/include/protobuf.inc#L56
https://github.com/alliedmodders/sourcemod/blob/master/plugins/include/protobuf.inc#L144
https://github.com/alliedmodders/sourcemod/blob/master/plugins/include/protobuf.inc#L214
https://github.com/ErikMinekus/sm-ripext/blob/main/pawn/scripting/include/ripext/json.inc#L116
https://github.com/ErikMinekus/sm-ripext/blob/main/pawn/scripting/include/ripext/json.inc#L172
...

2021-06-25 11:00 UTC, asherkin commented
Nice! This is a good interim solution and something I've been intending to add a format specifier for doing for ages.

Could you add some test cases to the test suite? (Or share a test plugin and test results here.)

2021-06-25 13:00 UTC, peace-maker commented
`BigInt` usually stands for some way to store any large number not restricted to 64 bits. Using Int64 might be more descriptive.

2021-06-25 17:18 UTC, dvander requested changes

2021-06-25 17:18 UTC, dvander commented on plugins/include/string.inc
> +native int BigIntToString(const int num[2], char[] str, int maxlength);
"Int64" instead of "BigInt"

2021-06-25 17:18 UTC, dvander commented on plugins/include/string.inc
> + * @return              Number of cells written to buffer.
The return comment should be:

"Number of characters written to the buffer, not including the null terminator"

2021-06-25 17:18 UTC, dvander commented on plugins/include/string.inc
> + * @param num           Big integer to convert.
"Array containing the upper and lower 32-bits of a 64-bit integer"

2021-06-25 17:18 UTC, dvander commented on plugins/include/string.inc
> + * @param result        Variable to store the result in.
"Array to store the upper and lower 32-bits of the 64-bit integer."

2021-06-28 17:32 UTC, dvander approved these changes

2021-06-28 19:17 UTC, asherkin commented
I wonder if `Int64ToString` should be a format specifier <instead / as well>? I imagine most of the use cases are going to be embedding one in a larger string such as a URL or SQL query.

2021-06-28 20:00 UTC, dvander commented
I'm ambivalent. Using int64 ids as anything other than strings is a bad idea unless there's some mathematical calculation going on. As numbers they are not portable to other languages (eg JavaScript/JSON).

2021-06-28 20:51 UTC, asherkin approved these changes

2021-06-28 20:51 UTC, merged