Add new natives for request/send file from client
alliedmodders/sourcemod pull request #1630
Opened 2021-11-04 12:47 UTC by Accelerator74

I thought these natives would be useful in sourcemod. They can help validate client files (`RequestFile`) or additionally identify them by unique files (`SendFile`) for each client. In addition, sdktools includes forwards `OnFileSend` and` OnFileReceive`.

2021-11-12 07:27 UTC, KyleSanderson commented
I'm under the impression that this doesn't work on newer games like csgo. Is that wrong?

2021-11-12 09:02 UTC, Accelerator74 commented
This works for csgo. But in order for the server to download files, the `sv_allowupload` value must be equal to 1. Also, in order for the client to receive files from the server, the client needs to bring the `sv_allowupload` cvar to the value 1. In general, the functions work fine :+1:
![test](https://user-images.githubusercontent.com/18032476/141440265-062c08bc-6c31-470b-b555-6923ef15df30.png)

2021-11-22 11:53 UTC, asherkin requested changes
There are at least two extensions that expose these functions for plugins already (LateDL and FileNetMessages), do we have any numbers on how widely those are used?

How do these natives interact with the existing forwards in SM? Particularly when the forward denies the transfer.

A user on Discord had a bunch of performance issues with the existing extensions that expose these functions due to not having a way to detect if a file transfer was already in progress, do we need to expose that here to make these usable? https://discord.com/channels/335290997317697536/335290997317697536/904900799778410576

2021-11-22 11:53 UTC, asherkin commented on extensions/sdktools/vnatives.cpp
> +#endif
Returning the transfer ID doesn't seem valuable unless we expose it elsewhere - is there value in adding it to the forwards for cross-referencing with requests here, or just ignore it?

2021-11-22 11:53 UTC, asherkin commented on plugins/include/sdktools_functions.inc
> + * @param ...             Variable number of format parameters.
It's not obvious what these are format parameters for - these natives being format-class seems wrong though, `BuildPath` should be used for paths in many cases and it would be very easy to break the format rules here and pass a non-literal as the format string.

2021-11-22 15:43 UTC, Accelerator74 commented
I think you are right that adding `RequestFile` and `SendFile` natives is not practical. These are very narrowly focused functions, which, moreover, do not work quite correctly everywhere, besides, we can still limit yourself to the extensions you mentioned. 👍

2021-11-22 15:44 UTC, closed without merging