Fix menu vote handler to work with direct arrays.
alliedmodders/sourcemod pull request #1643
Opened 2021-11-18 02:51 UTC by dvander

2021-11-18 19:24 UTC, PerfectLaugh requested changes
Have to fix the sourcepawn with this PR https://github.com/alliedmodders/sourcepawn/pull/716

2021-11-18 19:24 UTC, PerfectLaugh commented on core/logic/smn_menus.cpp
> +	if (!ok) {
This is not okay

2021-11-18 19:24 UTC, PerfectLaugh commented on core/logic/smn_menus.cpp
> +										"Menu callback could not allocate cells for client list.");
better to add %d into the message

2021-11-20 18:47 UTC, dvander commented on core/logic/smn_menus.cpp
> +										"Menu callback could not allocate cells for client list.");
The number is kind of meaningless. It's not accurate given that we allocate metadata behind the scenes, and at most it'll be a pretty small number.

2021-11-20 18:48 UTC, dvander commented
Latest patch uses AutoEnterHeapScope instead of HeapPop, which is now basically deprecated.

2021-11-26 23:02 UTC, asherkin approved these changes
I assume this doesn't need the SP pin update any more?

2021-11-26 23:40 UTC, Headline approved these changes

2021-12-10 02:14 UTC, merged