Add block parameter to ArrayList.FindString
alliedmodders/sourcemod pull request #1656
Opened 2021-11-28 05:02 UTC by Mikusch

This PR adds a `block` parameter to `ArrayList.FindString`, similar to `ArrayList.FindValue`. Default value is 0.

This can be useful when searching for strings in enum structs:
```sourcepawn
enum struct MyStruct
{
	int intValue;
	char strValue[64];
}

public void OnPluginStart()
{
	MyStruct struct1;
	struct1.intValue = 42;
	strcopy(struct1.strValue, sizeof(struct1.strValue), "foo");
	
	MyStruct struct2;
	struct2.intValue = 1337;
	strcopy(struct2.strValue, sizeof(struct2.strValue), "bar");
	
	ArrayList list = new ArrayList(sizeof(MyStruct));
	list.PushArray(struct1);
	list.PushArray(struct2);
	
	int index = list.FindString("bar", MyStruct::strValue);
	
	// This will print "Index: 1"
	PrintToServer("Index: %d", index);
}
```

2021-11-28 05:09 UTC, JoinedSenses commented
I like this. Would also be nice to have block param for (G/S)et(String/Array), too

2021-11-28 05:41 UTC, Mikusch commented
> Would also be nice to have block param for (G/S)et(String/Array), too

That sounds like a great addition. I'll get around to it in the coming days. I don't really mind if it's in this PR or another.

I should probably add an offset parameter to `CellArray::at` to make this look a bit cleaner.

2021-11-28 14:07 UTC, Mikusch commented
I've added the block parameter to (G/S)et(String/Array) and updated the PR name/description.

2023-07-03 18:37 UTC, peace-maker commented
@Mikusch can you rebase and fix the buffer overflow @sirdigbot mentioned please?

2023-07-30 23:51 UTC, Mikusch commented
Hi @peace-maker, I apologize for how long it's taken me to update this PR.

bb918f2bbc4ef44350e6dfd8e792f2ea65305347 adds an optional `size` parameter to `SetString` which will ensure you can't overflow the buffer.

2023-09-27 13:15 UTC, peace-maker requested changes
Looks good!

2023-09-27 13:15 UTC, peace-maker commented on plugins/include/adt_array.inc
> +native int SetArrayString(Handle array, int index, const char[] value, int block=0);
This needs the `int size=-1` parameter too.

2023-09-27 13:50 UTC, peace-maker approved these changes

2023-09-27 14:05 UTC, merged