ZPS: Add missing offsets
alliedmodders/sourcemod pull request #1719
Opened 2022-02-20 13:26 UTC by xerox8521

Adds support for the SDKHook Types: OnTakeDamage_Alive, GroundEntChanged, GetMaxHealth, Blocked and Reload.
Adds support for GivePlayerAmmo native.

I would have added them earlier but wasn't aware they were missing entirely.

2022-02-20 14:06 UTC, xerox8521 commented
The last 2 commits weren't supposed to be in this PR. I wanted them in a seperate one and I'm not entirely sure how to split these.

2022-02-22 01:14 UTC, KyleSanderson requested changes

2022-02-22 01:14 UTC, KyleSanderson commented on extensions/sdktools/vnatives.cpp
> +#if SOURCE_ENGINE == SE_SDK2013
Something is wrong here.

2022-02-22 16:45 UTC, xerox8521 commented on extensions/sdktools/vnatives.cpp
> +#if SOURCE_ENGINE == SE_SDK2013
Can you clarify? Apart that the change was supposed to be in a different PR.
The check is basically like this one here: https://github.com/alliedmodders/sourcemod/blob/master/extensions/sdktools/vnatives.cpp#L405

2022-02-23 00:10 UTC, psychonic commented on extensions/sdktools/vnatives.cpp
> +#if SOURCE_ENGINE == SE_SDK2013
What is the issue with leaving bForce as false? Does it just not do anything?

2022-02-23 08:43 UTC, peace-maker commented on extensions/sdktools/vnatives.cpp
> +#if SOURCE_ENGINE == SE_SDK2013
The preprocessor directive you added makes the native do nothing on any other engine than sdk2013.
You could refactor it to use a `bool bForce` variable which defaults to `false` and is set to true for zps.

2022-02-23 13:57 UTC, xerox8521 commented on extensions/sdktools/vnatives.cpp
> +#if SOURCE_ENGINE == SE_SDK2013
> What is the issue with leaving bForce as false? Does it just not do anything?

If set to false the action is delayed. So if you slay someone or timebomb explode the explosion happens and then nothing until the delay is finished.

> The preprocessor directive you added makes the native do nothing on any other engine than sdk2013. You could refactor it to use a `bool bForce` variable which defaults to `false` and is set to true for zps.

Oh yea I see will fix that up

2022-04-16 03:07 UTC, Headline commented
@KyleSanderson updates?

2022-04-16 14:06 UTC, psychonic approved these changes

2022-04-16 14:07 UTC, merged