Clientprefs helpers for integers and strings
alliedmodders/sourcemod pull request #1727
Opened 2022-03-11 15:25 UTC by eyal282

Title

2022-03-11 16:14 UTC, MAGNAT2645 commented
1) You shouldn't use `MarkNativeAsOptional` because these methods are not natives.
2) `Cookie.Get` returns empty string if there's no cookie stored for specific client. `StringToInt` in this case will return `0` and you can't really tell if that's the real value stored or that's the default value returned by `StringToInt` due to invalid (non-numeric or empty) string. I think it should be useful to provide default value if there's no cookie stored. For example:
```sourcepawn
	public int GetInt(int client, int defaultValue = 0) {
		char sValue[11];
		this.Get(client, sValue, sizeof(sValue));

                int value;
                if (!StringToIntEx(sValue, value))
                       value = defaultValue;
		return value;
	}

	public float GetFloat(int client, float defaultValue = 0.0) {
		char sValue[11];
		this.Get(client, sValue, sizeof(sValue));

                float value;
                if (!StringToFloatEx(sValue, value))
                       value = defaultValue;
		return value;
	}
```

2022-03-14 14:33 UTC, eyal282 commented
> 1. You shouldn't use `MarkNativeAsOptional` because these methods are not natives.
> 2. `Cookie.Get` returns empty string if there's no cookie stored for specific client. `StringToInt` in this case will return `0` and you can't really tell if that's the real value stored or that's the default value returned by `StringToInt` due to invalid (non-numeric or empty) string. I think it should be useful to provide default value if there's no cookie stored. For example:
> 
> ```sourcepawn
> 	public int GetInt(int client, int defaultValue = 0)
> 	{
> 		char buffer[11];
> 		this.Get(client, buffer, sizeof(buffer));
> 
>                 int value;
>                 if (!StringToIntEx(buffer, value))
>                 {
>                        value = defaultValue;
>                 }
> 		return value;
> 	}
> 
> 	public float GetFloat(int client, float defaultValue = 0.0)
> 	{
> 		char buffer[11];
> 		this.Get(client, buffer, sizeof(buffer));
> 
>                 float value;
>                 if (!StringToFloatEx(buffer, value))
>                 {
>                        value = defaultValue;
>                 }
> 		return value;
> 	}
> ```

I made the suggested changes you gave.

2022-03-31 07:32 UTC, MartLegion commented
In case this is approved, would be nice having something like that for DispatchKeyValue as well

2022-07-11 09:57 UTC, peace-maker requested changes
Those seem nice to have. Some comments inline.

2022-07-11 09:57 UTC, peace-maker commented on plugins/include/clientprefs.inc
> +                int value;
Mix of tabs and spaces.

2022-07-11 09:57 UTC, peace-maker commented on plugins/include/clientprefs.inc
> +		char buffer[11];
Is the largest float really only 10 characters long? I wouldn't prematurely optimize buffer sizes and just use some large-enough power of two.

2022-07-12 22:16 UTC, MartLegion commented on plugins/include/clientprefs.inc
>  	// Retrieve the value of a Client preference cookie.
SetFloat still small [11]

2022-07-13 07:16 UTC, peace-maker commented on plugins/include/clientprefs.inc
>  	// Retrieve the value of a Client preference cookie.
I'm talking about the comment I've commented on on line 136/161. You changed the docs for `.Set` to say "string value", so the docs for `.Get` could say that as well. It's not that important, sorry for not being clear.

2022-07-13 14:07 UTC, peace-maker requested changes

2022-07-13 14:07 UTC, peace-maker commented on plugins/include/clientprefs.inc
> +		char sValue[11];
Same comment about buffer size for large float values applies here too I think.

2022-07-13 14:07 UTC, peace-maker commented on plugins/include/clientprefs.inc
> +                }
Still lots of mixed tabs and spaces. I didn't comment on every line, but only wanted to point out the general problem with your changes.

2022-07-31 09:58 UTC, peace-maker approved these changes
Thank you for this!

2022-07-31 09:59 UTC, merged