Allow ROOT flag to call public votes
alliedmodders/sourcemod pull request #1730
Opened 2022-03-22 21:41 UTC by AGabenMan

This patch allow ROOT flag to call votes even if a delay is set. Its nice to have the possibility to set a delay betweens votes to limit public votes. Generally, we do this when we have lots of admins. But as a ROOT flag this limit shall no be set.

2022-03-22 21:45 UTC, asherkin requested changes
This seems like a good feature to have, but please change the implementation to use CheckCommandAccess with a suitable override string.

2022-03-22 23:52 UTC, AGabenMan commented
I propose an override sm_vote_access

2022-03-23 19:53 UTC, AGabenMan commented
@asherkin what do you think of the new update ?

2022-03-26 17:23 UTC, AGabenMan reviewed
Fixed

2022-04-10 19:45 UTC, GabenManPowered commented
Hello, I was the originator of #1730 but I have lost my git account, so I have created a new one.

Can you reopen PR #1733 and close this PR instead please ?

Then I can make the new update as proposed by  @Kenzzer 

Thanks

2022-04-11 08:55 UTC, closed without merging