Remove reply source check for sm_nominate with no args
alliedmodders/sourcemod pull request #1803
Opened 2022-07-18 14:51 UTC by dysphie

This reverts a change introduced in PR https://github.com/alliedmodders/sourcemod/commit/b8fd7db58d34c9ee5c0b9f2a6cea844f9d978fdb where `sm_nominate` can no longer be used from console to bring up the map menu. I don't see a reason for this existing (correct me if I'm wrong) and it's a slight annoyance for people who use binds (or `sm_n` + autocomplete)

2022-07-18 15:35 UTC, Headline requested changes

2022-07-18 15:43 UTC, JoinedSenses commented on plugins/nominations.sp
> -		if (source == SM_REPLY_TO_CHAT)
Im pretty sure this behavior currently exists because I didn't want to remove the usage response, but this change seems to make more sense tbh. It's been so long, I can't properly remember the thought process here.

2022-07-18 17:23 UTC, Headline commented on plugins/nominations.sp
> -		if (source == SM_REPLY_TO_CHAT)
got it, thanks. I think popping the menu up is more of a first class feature than explaining how the Console command can be used with arguments so I'm in favor of this PR's direction. 

Your thought process before on this makes sense and is valid, though.

2022-07-18 18:18 UTC, Headline approved these changes

2022-07-26 20:09 UTC, peace-maker approved these changes

2022-07-26 20:09 UTC, merged