Update SDKCall return information
alliedmodders/sourcemod pull request #1961
Opened 2023-03-29 03:36 UTC by xerox8521

This adds the information that if the return value is a string then SDKCall will return the number of bytes written. See [here](https://github.com/alliedmodders/sourcemod/blob/master/extensions/sdktools/vcaller.cpp#L507)

I'm not entirely sure if the description given is clear enough or if it may cause confusion.
I'm open for suggestions.

2023-03-30 00:52 UTC, nosoop commented on plugins/include/sdktools.inc
> + * If the return value is a string, then the number of bytes written will be this value.
Should be "If the return value is a string, the return value will be the number of bytes written."

Though in my opinion, "the value returned by the function" makes more sense for the second instance of "return value" in this section, since it seems clunky that the term refers to both the value returned by the underlying game function and the `SDKCall` native itself.

2023-03-30 13:40 UTC, xerox8521 commented on plugins/include/sdktools.inc
> + * If the return value is a string, then the number of bytes written will be this value.
Updated the description text.

2023-03-31 15:20 UTC, peace-maker requested changes

2023-03-31 15:44 UTC, xerox8521 commented on plugins/include/sdktools.inc
> + * If the return value is a string, the value returned by the function will be the number of bytes written.
I'm assuming bytes written will be 0 then if the actual string is empty.

2023-03-31 15:47 UTC, peace-maker commented on plugins/include/sdktools.inc
> + * If the return value is a string, the value returned by the function will be the number of bytes written.
https://github.com/alliedmodders/sourcemod/blob/dd1e5997f3abc40f09a2c60423ad47f8989d4043/extensions/sdktools/vcaller.cpp#L498-L507

2023-03-31 15:49 UTC, xerox8521 commented on plugins/include/sdktools.inc
> + * If the return value is a string, the value returned by the function will be the number of bytes written.
Ah, my bad was thinking about StringToLocalUTF8 itself rather than the native itself.

2023-03-31 16:00 UTC, peace-maker approved these changes

2023-04-02 21:46 UTC, merged