Update Slovak nominations.phrases.txt
alliedmodders/sourcemod pull request #2003
Opened 2023-05-29 05:34 UTC by luki1412

Added missing phrase

2023-06-12 20:36 UTC, peace-maker requested changes

2023-06-12 20:36 UTC, peace-maker commented on translations/sk/nominations.phrases.txt
> +		"#format"	"{1:s}"
`#format` should only be used in the english base translation files.

2023-06-12 21:11 UTC, luki1412 commented on translations/sk/nominations.phrases.txt
> +		"#format"	"{1:s}"
Removed

2023-06-13 08:10 UTC, peace-maker approved these changes
Thank you!

2023-06-13 08:10 UTC, merged