Clarify timer precision
alliedmodders/sourcemod pull request #2009
Opened 2023-06-29 06:52 UTC by sapphonie

Common footgun, should be clarified

2023-06-30 13:44 UTC, peace-maker requested changes
Even though this is an [implementation detail](https://github.com/alliedmodders/sourcemod/blob/6ebf04b75d82322f1e7729b3fbbdd645f77f9ec1/core/TimerSys.cpp#L39), it's a common source of confusion, so worth adding a note. Thank you!

2023-07-01 06:20 UTC, sapphonie commented on plugins/include/timers.inc
> + *                      Timer intervals are rounded to the nearest tenth of a second.
Honestly, after talking about it in the SM discord, I *still* don't quite understand what is going on with timer precision - as far as I know, it just executes on a think every 100ms, but a global think and not a per timer think?

2023-07-01 15:33 UTC, dvander commented
It's driven by the framerate, so it's not super accurate or precise.On Jun 30, 2023 11:20 PM, sappho ***@***.***> wrote:
@sapphonie commented on this pull request.



In plugins/include/timers.inc:
>   *
  * @param interval      Interval from the current game time to execute the given function.
+ *                      Timer intervals are rounded to the nearest tenth of a second.

Honestly, after talking about it in the SM discord, I still don't quite understand what is going on with timer precision - as far as I know, it just executes on a think every 100ms, but a global think and not a per timer think?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-07-08 12:48 UTC, Frenzoid approved these changes

2023-07-11 03:51 UTC, sapphonie commented
Closing in favor of #2014 , will reopen if that PR fails

2023-07-11 03:51 UTC, closed without merging