Tick timers every tick instead of arbitrarily on 100ms thinks, adding a significantly higher amount of precision
alliedmodders/sourcemod pull request #2014
Opened 2023-07-03 08:36 UTC by sapphonie

Lightly tested, no significant impact on performance I can see, though it should probably be tested a bit more heavily...

2023-07-04 04:17 UTC, KyleSanderson commented
The wait is in there because there were issues with timers running over eachother (0.0 into a 0.0 into a 0.0... etc). At least this is my memory of the issue when I proposed the same thing many years ago.

2023-07-04 08:34 UTC, sapphonie commented
> The wait is in there because there were issues with timers running over eachother (0.0 into a 0.0 into a 0.0... etc). At least this is my memory of the issue when I proposed the same thing many years ago.

If this is the case, it should be as simple as setting the think time to the tick interval?

2023-07-11 01:14 UTC, KyleSanderson commented
Please consider keeping things like this in the same issue if they're directly related to one another. I'm closing this in favour of https://github.com/alliedmodders/sourcemod/pull/2009 where the discussion should continue around this if desired.

2023-07-11 01:46 UTC, dvander commented
Why close? This is a valid PR and orthogonal to the other one. I think this idea should be entertained for simplicity at least...On Jul 10, 2023 6:14 PM, Kyle Sanderson ***@***.***> wrote:
Closed #2014.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
On Jul 10, 2023 6:14 PM, Kyle Sanderson ***@***.***> wrote:
Closed #2014.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
On Jul 10, 2023 6:14 PM, Kyle Sanderson ***@***.***> wrote:
Closed #2014.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-07-11 04:08 UTC, sapphonie commented
> The wait is in there because there were issues with timers running over eachother (0.0 into a 0.0 into a 0.0... etc). At least this is my memory of the issue when I proposed the same thing many years ago.

Do you know of an easy way to make a test case for this? I'm not sure what you mean, do you mean multiple timers running at 0.0? One single timer running at 0.0 executing infinitely? Or wha? I think regardless these could be easily solved by just limiting timers to <tickinterval> which is probably what users expect anyway

2023-07-11 04:10 UTC, sapphonie commented
Could also do something like

```c
...
        float tickInterval = g_ServerGameDLL.GetTickInterval(); /* or whatever the function would be */

	if (g_fUniversalTime >= g_fTimerThink)
	{
		RunFrame();
		g_fTimerThink = CalcNextThink(g_fTimerThink, tickInterval );
	}
...
```

2023-07-12 18:30 UTC, dvander approved these changes
Seems fine to me, timers have lots of idiosyncracies but it's not like this can't be reverted if something blows up somewhere.

I think a timer with an interval of 0.0 firing constantly would only be a problem if there were ticks happening < interval_per_tick.

2023-07-12 21:03 UTC, KyleSanderson commented
> > The wait is in there because there were issues with timers running over eachother (0.0 into a 0.0 into a 0.0... etc). At least this is my memory of the issue when I proposed the same thing many years ago.
> 
> Do you know of an easy way to make a test case for this? I'm not sure what you mean, do you mean multiple timers running at 0.0? One single timer running at 0.0 executing infinitely? Or wha? I think regardless these could be easily solved by just explicitly limiting timers to <tickinterval> which is probably what users expect anyway

CreateTimer, in that callback, create another timer, and keep doing that. It may have been from when time was a float as opposed to a double, but do they run properly?

2023-07-26 09:49 UTC, sapphonie commented
dammit

2023-08-04 17:32 UTC, Headline commented
Documenting some discussion that happened on Discord: 

What worries me here is that previous reliance on tick behavior definitely will cause breakage. Adding a timer flag, something along the lines of TIMER_FLAG_TICK_PRECISE, will expand functionality here for higher precision timers without breaking bcompat behavior-wise.

2025-09-19 07:39 UTC, Headline commented
Requested KyleS to take a look, effort here was to maintain "dont pay for what you don't use"

Essentially we just calculate ToExec in different ways depending on the list the timer is in

2025-09-19 08:16 UTC, Headline requested changes

2025-09-19 08:16 UTC, Headline commented on core/TimerSys.cpp
> +        List<ITimer*> timerList = pTimer->m_Flags & TIMER_FLAG_TICK_PRECISE ? m_HighSpeedLoopTimers : m_LowSpeedLoopTimers;
all of these are supposed to be references and not copies- will fix

this pattern is used a few times

2026-09-04 04:44 UTC, Headline approved these changes

2026-09-06 08:19 UTC, merged