Update basebans.phrases.txt
alliedmodders/sourcemod pull request #2050
Opened 2023-09-26 17:30 UTC by roprop1

added all the missing Phrase

2023-10-17 10:39 UTC, peace-maker requested changes
Thank you! Can you add the hint for the `!abortban` command too please?

2023-10-17 10:39 UTC, peace-maker commented on translations/he/basebans.phrases.txt
> +		"he"		"הסבר סיבת ההשעייה המותאמת"
This phrase as a parameter which you'd need to include in your translation.

https://github.com/alliedmodders/sourcemod/blob/44aaaf8b103119fc85b41f07402915f42a8ade52/translations/basebans.phrases.txt#L56

2023-11-24 09:58 UTC, roprop1 commented on translations/he/basebans.phrases.txt
> +		"he"		"הסבר סיבת ההשעייה המותאמת"
I updated the missing phrase as a parameter

2023-11-24 15:55 UTC, peace-maker approved these changes

2023-11-24 15:56 UTC, merged