make RenameFile() on Windows also replace the file
alliedmodders/sourcemod pull request #2060
Opened 2023-10-09 02:42 UTC by rtldg

2023-10-09 02:44 UTC, rtldg commented
accidentally made the pr on this repo instead my fork when trying to test github actions building the binary for testing. if the binary works correctly though then I'll keep the pr open

2024-05-05 21:25 UTC, psychonic requested changes
Looking at the available flags, I think we should probably add `MOVEFILE_COPY_ALLOWED` as well

2024-05-05 22:11 UTC, rtldg commented
> Looking at the available flags, I think we should probably add `MOVEFILE_COPY_ALLOWED` as well

Good idea. Added it.

2024-05-05 22:20 UTC, psychonic approved these changes
Thanks

2024-05-05 22:20 UTC, merged