mcv update gamedata
alliedmodders/sourcemod pull request #2066
Opened 2023-10-15 15:37 UTC by sapphonie

NOT DONE YET

2023-11-29 08:28 UTC, amnestria commented
### Environment
- Operating System version: Debian 11
- Current SourceMod version: 1.12 Dev
- Current Metamod: Source version: 1.12 Dev

### Description
I am unable to load Metamod due to the following errors:

`metamod-fatal.log`
```
L 11/29/2023 - 00:06:50: Detected engine 25 but could not load: /home/container/vietnam/addons/metamod/bin/linux64/metamod.2.mcv.so: undefined symbol: g_pCVar
```

`Console`
```
Failed to load plugin "addons/metamod/bin/linux64/server"
Failed to dlopen /home/container/vietnam/addons/metamod/bin/server.so error=/home/container/vietnam/addons/metamod/bin/server.so: wrong ELF class: ELFCLASS32
 ```

2023-11-29 08:59 UTC, sapphonie commented
> ### Environment
> 
>     * Operating System version: Debian 11
> 
>     * Current SourceMod version: 1.12 Dev
> 
>     * Current Metamod: Source version: 1.12 Dev
> 
> 
> ### Description
> 
> I am unable to load Metamod due to the following errors:
> 
> `metamod-fatal.log`
> 
> ```
> L 11/29/2023 - 00:06:50: Detected engine 25 but could not load: /home/container/vietnam/addons/metamod/bin/linux64/metamod.2.mcv.so: undefined symbol: g_pCVar
> ```
> 
> `Console`
> 
> ```
> Failed to load plugin "addons/metamod/bin/linux64/server"
> Failed to dlopen /home/container/vietnam/addons/metamod/bin/server.so error=/home/container/vietnam/addons/metamod/bin/server.so: wrong ELF class: ELFCLASS32
> ```

Try this on metamod source 2.0

2024-02-09 19:03 UTC, Gazyi requested changes
Updated some Windows signatures and offsets ( Build from 7 February 2024 ).

2024-02-09 20:01 UTC, sapphonie commented
> Updated some Windows signatures and offsets ( Build from 7 February 2024 ).

PR these to my fork, please, thanks. In the process of updating other things as well, but this should work as a stopgap. Thanks!

2026-07-07 03:24 UTC, closed without merging