Handle `INVALID_FUNCTION` mismatches at plugin boundaries
alliedmodders/sourcemod pull request #2071
Opened 2023-10-28 11:55 UTC by nosoop

Translates the following uses of `INVALID_FUNCTION` for compatibility between plugins compiled before and after the SourcePawn changes:

- `GetNativeFunction`
- `Call_StartFunction` (probably unnecessary since trying to call a null function shouldn't? work)
- `DataPack`s now store `INVALID_FUNCTION` as 0 internally and retrieved based on caller's context

This should make it so plugins can remain mostly compatible regardless of what value of `INVALID_FUNCTION` they are compiled with.  Function coercion to values was disallowed a while back so I'd imagine most plugins communicate their use of functions through these three avenues.

I confirmed the behavior is correct for `GetNativeFunction`; the other two are untested.

2023-10-28 19:02 UTC, dvander requested changes
Great idea, thanks for doing this!

2023-10-28 19:02 UTC, dvander commented on core/logic/smn_functions.cpp
> +		s_pFunction = pTargetContext->GetFunctionById(pTargetContext->GetNullFunctionValue());
I think you can just assign nullptr here?

2023-10-29 07:09 UTC, nosoop commented
One edge case I'm starting to see:

1.  Old plugin passes a non-`INVALID_FUNCTION` funcid 0 to new plugin.
2.  New plugin retrieves it (via `GetNativeFunction` and `DataPack.ReadFunction`) as funcid 0 and ends up being treated as `INVALID_FUNCTION`.

I think the simplest workaround would be to map a valid 0th function from a legacy plugin to a special value.  Will work that out shortly.

2023-10-29 07:10 UTC, nosoop commented on core/logic/smn_functions.cpp
> +		s_pFunction = pTargetContext->GetFunctionById(pTargetContext->GetNullFunctionValue());
Yeah.  I didn't look into the implementation too deeply earlier; I think it's fine just to check that it's not the caller's null function ID and then do `GetFunctionByIdOrNull()`, otherwise leave it as NULL (as that was set earlier via `ResetCall()`).  Plus some extra handling for legacy valid 0 funcids.

2023-10-29 11:20 UTC, nosoop commented
Couple of other boundaries that I need to address:

- `AddToForward` / `PrivateForward.AddFunction`
- `RemoveFromForward` / `PrivateForward.RemoveFunction`
- `GetFunctionByName`

2023-10-29 11:35 UTC, nosoop commented
Actually, can function IDs ever be zero?  Just found `PublicIndexToFuncId`, and that always sets the LSB to 1 so it sounds like a non-null function ID of 0 shouldn't exist.

2023-10-29 22:20 UTC, dvander commented
Right, zero is never valid. It's just a question of silent/intended failure vs reported error.

2023-11-03 04:38 UTC, closed without merging

2023-11-03 05:51 UTC, nosoop commented
Will rebase, revert the 0 function handling, and reopen this against master shortly.