Modernize Sample Extensions's AMBuildScript
alliedmodders/sourcemod pull request #2107
Opened 2024-01-27 17:02 UTC by caxanga334

# Summary
This PR aims to modernize the AMBuildScripts of the sample extensions. Bringing them closer to SM own AMBuildScript and adding support for compiling 64 bits extensions.

## Sample 
The build script is based on SM own build script. It was updated to use the HL2SDK manifests and allow compiling for multiple archs. Minimum AMBuild version increased to 2.2.

Two new arguments added to configure.py.

- --hl2sdk-manifest-path : Path to the HL2SDK manifests, this is optional if the manifests already exists in the project root. Otherwise a copy of the manifests is created on the project root folder.
- --targets : Overrides target build arch.

## Sample (NO SDK)
The build script was updated to allow compiling for multiple archs. Minimum AMBuild version increased to 2.2.

One new argument added to configure.py.

- --targets : Overrides target build arch.

2024-04-12 17:08 UTC, FortyTwoFortyTwo commented on public/sample_ext/AMBuilder
> +    binary = Extension.HL2ExtConfig(project, builder, cxx, extName + sdk['extension'], sdk)
Missing a dot at `extName + sdk['extension']`? I tried to compile it, got `tank.ext2.tf2.so` instead of `tank.ext.2.tf2.so`

2024-04-12 17:20 UTC, caxanga334 commented
Hi @FortyTwoFortyTwo . Yeah I indeed missed a dot. Updated the scripts. Could you please test again?

2024-04-12 23:29 UTC, FortyTwoFortyTwo commented
> Hi @FortyTwoFortyTwo . Yeah I indeed missed a dot. Updated the scripts. Could you please test again?

All works fine for Linux, though trying in windows gives me `LINK : warning LNK4044: unrecognized option`, ignoring four TF2 windows libs. Not sure if it's my fault or it's the build script.

2024-04-13 13:48 UTC, caxanga334 commented
> All works fine for Linux, though trying in windows gives me `LINK : warning LNK4044: unrecognized option`, ignoring four TF2 windows libs. Not sure if it's my fault or it's the build script.

I was unable to reproduce this when compiling the **sample_ext**. Tried both x86 and x86_64 MSVC.

2024-05-13 18:04 UTC, bottiger1 commented
Thanks for the update. However I noticed that when you use -static-libstdc++ it crashes when you pipe a number bigger than a char into iostream like this.

`std::cout << (uintptr64_t)123;`

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1db217b09b in char32_t std::(anonymous namespace)::read_utf8_code_point<char>(std::(anonymous namespace)::range<char const, true>&, unsigned long)
#1  0x00007f1db217cf3f in std::codecvt_base::result std::(anonymous namespace)::utf16_in<char, char16_t>(std::(anonymous namespace)::range<char const, true>&, std::(anonymous namespace)::range<char16_t, true>&, unsigned long, std::codecvt_mode, std::(anonymous namespace)::surrogates) ()
#2  0x00007f1db217d0a4 in std::codecvt<char16_t, char, __mbstate_t>::do_in(__mbstate_t&, char const*, char const*, char const*&, char16_t*, char16_t*, char16_t*&) const ()
#3  0x00007f1db21df14a in std::ostream& std::ostream::_M_insert<unsigned long>(unsigned long) ()
#4  0x00007f1db2107c1d in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > PLH::int_to_hex<unsigned long>(unsigned long) ()
#5  0x00007f1db20fff0e in PLH::x64Detour::hook()
```

I am not sure we can do anything about this or whether it is preferential to dynamically link to stdc++ instead. 

However if we don't statically link to stdc++ it would mean extensions wouldn't be able to load on an OS running older versions of stdc++ which seems to be quite often. stdc++ versions often change every OS release.

2024-05-13 20:53 UTC, Kenzzer commented
> I am not sure we can do anything about this or whether it is preferential to dynamically link to stdc++ instead. SRCDS appears to dynamically link.

The issue is loosely connected to alliedmodders/metamod-source#167 the fix from that part needs to be backported to metamod 1.12

And applied there as well (that's how extensions are loaded)
https://github.com/alliedmodders/amtl/blob/e38cfe3cbf2047916e4a68017840bd325a8f7080/amtl/os/am-shared-library.h#L64

2024-05-13 21:38 UTC, bottiger1 commented
> > I am not sure we can do anything about this or whether it is preferential to dynamically link to stdc++ instead. SRCDS appears to dynamically link.
> 
> The issue is loosely connected to [alliedmodders/metamod-source#167](https://github.com/alliedmodders/metamod-source/pull/167) the fix from that part needs to be backported to metamod 1.12
> 
> And applied there as well (that's how extensions are loaded) https://github.com/alliedmodders/amtl/blob/e38cfe3cbf2047916e4a68017840bd325a8f7080/amtl/os/am-shared-library.h#L64

I'm assuming you mean sourcemod? It is already in metamod.

I just added RTLD_DEEPBIND, recompiled sourcemod, and it still crashes.

2024-05-13 22:09 UTC, Kenzzer commented
> I'm assuming you mean sourcemod? It is already in metamod.

I did mean metamod. Currently the fix was applied to metamod 2.0, not 1.12. I was pointing this out in the event an extension is compiled as a metamod plugin, as it will be loaded by metamod instead.

> I just added RTLD_DEEPBIND, recompiled sourcemod, and it still crashes.

Hmmm, I'll try investigating as well when I get the chance.

2024-05-13 22:19 UTC, bottiger1 commented
I just checked, I'm already using 2.0, and double checked that it has the deepbind change.

 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1289
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: Valve Server Plugin
    Compiled on: Apr 20 2024 14:02:31
    Built from: https://github.com/alliedmodders/metamod-source/commit/b4aa055
    Build ID: 1289:b4aa055
    http://www.metamodsource.net/

2024-10-21 08:55 UTC, Kenzzer requested changes

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext_nosdk/AMBuildScript
> +      if builder.backend != 'amb2':
https://github.com/alliedmodders/ambuild/blob/551dd3f630f90377cbe536fbaf12e0b6bca91253/ambuild2/frontend/amb2_gen.py#L40

Since you're forcing the api version to 2.2 in your configure.py file. That check is unnecessary.

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext_nosdk/AMBuildScript
> +      if cxx.version < 'gcc-9':
Nitpick, full C++17 support was actually achieved in gcc-8
https://gcc.gnu.org/projects/cxx-status.html

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext_nosdk/AMBuildScript
> +    # Optimizaiton
Please undo, lol.

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext_nosdk/AMBuildScript
> +    cxx.cxxflags += ['-std=c++17']
Merge this with the `cxx.cxxflags` right below.

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext_nosdk/AMBuildScript
> +    if cxx.version >= 'clang-3.9' or cxx.version == 'clang-3.4' or cxx.version > 'apple-clang-6.0':
Since we're forcing clang version 5 (and later). This check is unnecessary, also are those no-warning flags necessary to compile the sample extension. May I trouble you to just outright remove all of them, and verify if you can still compile the sample ext fine ?

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext_nosdk/AMBuildScript
> +      os.path.join(builder.sourcePath, 'public'),
Remove that line. This is going to create a lot of troubles.

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext/AMBuildScript
> +    return self.StaticLibraryBuilder(compiler, name)
Unneeded for the sample ext script. Should be deleted.

2024-10-21 08:55 UTC, Kenzzer commented on public/sample_ext/AMBuildScript
> +    return compiler.StaticLibrary(name)
Unneeded for the sample ext script. Should be deleted.

2024-10-21 23:21 UTC, caxanga334 commented
Hi, @Kenzzer 

I've made the changes you requested. Please review and see if I didn't forgot anything.

Both scripts compiled successfully on Debian with Clang 11.

2024-10-22 07:52 UTC, Kenzzer requested changes
Thanks for the changes! I spotted one more issue, my apologies for not catching it in the earlier review. Otherwise I believe this is good to merge.

2024-10-22 07:52 UTC, Kenzzer commented on public/sample_ext/AMBuildScript
> +        self.mms_root = ResolveEnvPath('MMSOURCE_DEV', 'metamod-source')
Accidental change ? Shouldn't it be `MMSOURCE` ?

2024-10-22 10:53 UTC, caxanga334 commented on public/sample_ext/AMBuildScript
> +        self.mms_root = ResolveEnvPath('MMSOURCE_DEV', 'metamod-source')
No. It comes from SM's AMBuildScript.

https://github.com/alliedmodders/sourcemod/blob/master/AMBuildScript#L133

2024-10-22 12:04 UTC, Kenzzer commented on public/sample_ext/AMBuildScript
> +        self.mms_root = ResolveEnvPath('MMSOURCE_DEV', 'metamod-source')
Then you should also match that change with your second AMBuildScript file.
https://github.com/alliedmodders/sourcemod/blob/9da7e650e63c629eb20af4dd50e6bcdc071be1a1/public/sample_ext_nosdk/AMBuildScript#L90

2024-10-22 12:12 UTC, Kenzzer approved these changes

2024-10-22 12:14 UTC, caxanga334 commented on public/sample_ext/AMBuildScript
> +        self.mms_root = ResolveEnvPath('MMSOURCE_DEV', 'metamod-source')
Done.

2024-10-25 16:28 UTC, Kenzzer commented
I'm ready to take this in. However I'd rather not shake up the build environments for current 3rd-party extensions, and introduce two competing standards, so I'm adding extra env var checks. Anyways, thanks for your work!

2024-10-25 16:58 UTC, merged