Add OnServerHibernationUpdate forward (closes #1483)
alliedmodders/sourcemod pull request #2151
Opened 2024-05-06 03:21 UTC by ojlanders

Adds the OnServerHibernationUpdate forward. OnServerHibernationUpdate_Post() isn't possible to implement because there would be no place for it to be called from after SV_Frame stops executing.
Link to Discord discussion.

2024-05-06 03:22 UTC, ojlanders commented
Test script:
```
#include <sourcemod>

public void OnServerHibernationUpdate(bool state)
{
    PrintToServer("Server hibernation state changed to: %s", state ? "true" : "false");
}
```
here's the output:
```
sm_cvar sv_hibernate_when_empty 0
[SM] Changed cvar "sv_hibernate_when_empty" to "0".
L 05/05/2024 - 23:11:48: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_hibernate_when_empty") (value "0")
Server waking up from hibernation
Server hibernation state changed to: false
sm_cvar sv_hibernate_when_empty 1
[SM] Changed cvar "sv_hibernate_when_empty" to "1".
L 05/05/2024 - 23:11:49: [basecommands.smx] "Console<0><Console><Console>" changed cvar (cvar "sv_hibernate_when_empty") (value "1")
Server is hibernating
Server hibernation state changed to: true
```

2024-05-06 04:36 UTC, Headline requested changes
Thanks! - I just have some dev-user clarifications from me

2024-05-06 04:36 UTC, Headline commented on plugins/include/clients.inc
> + * @param state         The new hibernation state.
new state? we should mention what true means here so it's clear we have begun hibernating, does false mean we have just awakened? Name it isHibernating

2024-05-06 04:36 UTC, Headline commented on plugins/include/clients.inc
> +forward void OnServerHibernationUpdate(bool state);
OnHibernationChanged? Update implies to me we're getting this every frame, but this could just be me..

2024-05-06 06:34 UTC, ojlanders commented on plugins/include/clients.inc
> + * @param state         The new hibernation state.
added a bit to explain thsi

2024-05-06 06:40 UTC, ojlanders commented on plugins/include/clients.inc
> +forward void OnServerHibernationUpdate(bool state);
in general there's not a better way to do this: the function name "ServerHibernationUpdate" is well known, and the proper nomenclature used both in the engine and in everywhere i've seen it (like master server comms) is "hibernation state" unfortunately

2024-05-06 17:19 UTC, Headline approved these changes

2024-05-07 01:42 UTC, psychonic approved these changes
Thanks

2024-05-07 01:44 UTC, merged