Introduce MemoryPointer
alliedmodders/sourcemod pull request #2196
Opened 2024-07-27 12:22 UTC by Kenzzer

_This whole PR is still an heavy draft, nothing has been field tested._

## Introduction

As of today no immediate solution to `PseudoAddress` has been explored. Only third-party solutions like [NotnHeavy/SM-Address64](https://github.com/NotnHeavy/SM-Address64) & [skial-com/port64](https://github.com/skial-com/port64) have been made, but no major adoption so far. And while those solutions can work, I believe the friction for plugin authors is quite high. Now having to worry about the server architecture, and the confusing concept of treating ptrs as array of int/any.

## Explanation

Given that there's no timeline as for when enum struct natives will ever be a thing. I propose instead to expose a new handle type that shall act as an opaque pointer towards abitrary memory regions. The underlying C++ class `IMemoryPointer` contained by the handle type is exposed as a public header. Allowing third-party extensions to wrap their pointers into it, no longer having to rely and depend on `cell_t` capacity to store the pointer's value on 32 bits.

`IMemoryPointer` shall become the defacto standard to pass abitrary pointers around for plugins & extensions.

### List of natives

`MemoryPointer.MemoryPointer(int size)`
Allocates an abitrary amount of memory.

`MemoryPointer.Load`
Similar to `LoadFromAddress` native.

`MemoryPointer.Store`
Similar to `StoreToAddress` native.

`SDKCall_MemoryPointer`
New sdkcall type to allow member function calls from the ptr contained by a MemoryPointer handle.

`SDKType_MemoryPointer`
New sdkparam type, to retrieve the abitrary ptr contained inside a `MemoryPointer` handle. `INVALID_HANDLE` / `null` are allowed values to represent nullptr, if allow null flag was passed.

Ultimately this PR aims to supersede #2159 & #2112

### Extra natives (will be added later)

`GameData.GetMemSigEx`
Similar to `GameData.GetMemSig` but wraps the pointer into a `MemoryPointer` handle.

`GetEntityMemoryPointer`
Similar to `GetEntityAddress` but wraps the pointer into a `MemoryPointer` handle.

2024-07-27 12:58 UTC, NotnHeavy commented
I think this is a decent work-around, considering the current `cell_t` limitations of SourcePawn and the numerous extensions that currently exist as a result of 64-bit address workarounds - including mine (which I hoped would've been the standard until an official SM native of some kind came around).

However, I feel like it's still missing out on some features, such as being able to wrap around existing addresses rather than only being able to use the handle to allocate a new block of memory. 

Perhaps natives for converting between pseudo addresses and `MemoryPointer` would also be ideal?

In the end as well this obviously creates a new issue of having to `delete` your `MemoryPointer` objects every time you use them as well, but I suppose active use of it wouldn't necessarily be encouraged.

2024-07-28 13:09 UTC, KaelaSavia commented
> In the end as well this obviously creates a new issue of having to `delete` your `MemoryPointer` objects every time you use them as well, but I suppose active use of it wouldn't necessarily be encouraged.

Perhaps it could be possible to have argument in MemoryPointer constructor that would decide whether pointer is freed on plugin end, or requires manual freeing. 

Also, would it be perhaps possible for "reasons" to have those two natives added?
- For converting two 32-bit ints (array) into MemoryPointer
- For converting MemoryPointer into array of two 32-bits


Other than that, current solution is pretty decent, people should be able to easily adapt. Although having wiki page just like we had for transistional syntax will make things even smoother, but thats not priority for now imo.

2024-07-29 08:40 UTC, Kenzzer commented
> Perhaps it could be possible to have argument in MemoryPointer constructor that would decide whether pointer is freed on plugin end, or requires manual freeing.

Purposefully leaking memory isn't something I'd advise. The standard in Sourcemod is that all plugin-instanced ressources are freed on unloading, this shouldn't be an exception. If a plugin or extension wants to keep a memorypointer around for longer, they're free to create their own and copy the data over.

2024-07-29 20:15 UTC, FortyTwoFortyTwo commented on plugins/include/sourcemod.inc
> +	public native Address GetAddressEx(const char[] name);
Missed here and `GetMemSigEx` having return field as `MemoryPointer`?

2024-07-30 02:55 UTC, psychonic approved these changes

2024-07-30 05:01 UTC, Headline requested changes
Most is nit picky or have already been pointed out

2024-07-30 12:42 UTC, Kenzzer commented on core/logic/MemoryPointer.cpp
> +	}
This is in the dtor, so m_ptr is never gonna be used again but I can fix it.

2024-07-30 12:44 UTC, Kenzzer commented on core/logic/smn_core.cpp
> +			((IMemoryPointer *)object)->Delete();
Given the nature of `IMemoryPointer` I cannot guarantee the method by which it was allocated in third party extensions. So calling `delete (IMemoryPointer*)object` would be ill advised, hence a delete method.

2024-07-30 12:45 UTC, Kenzzer commented on core/logic/smn_gameconfigs.cpp
> +	void* val;
This is just a straight copy of the original code. I assume if it passed review the first time around that yes `GetAddress` would initialise `val`.

2024-08-03 18:10 UTC, Headline approved these changes

2024-08-04 15:24 UTC, NotnHeavy commented
There's issues with using `SDKType_MemoryPointer`. These are addressed in [a PR I made to Kenzzer's PR](https://github.com/Kenzzer/sourcemod/pull/1).

2024-08-19 11:52 UTC, Kenzzer commented
We should be good to merge this time.

2024-08-22 15:18 UTC, dvander commented
It'll be a while. It's a slog if there ever was a slog. I'd branch if you need to.On Aug 22, 2024 10:28 AM, NotnHeavy ***@***.***> wrote:
The thing with 1.12 at the moment is that dvander is currently refactoring the SourcePawn compiler completely, to the point that int64 hypothetically may be introduced. I'm not sure if it will make sense to start 1.13 now.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-08-22 21:11 UTC, Kenzzer commented
> The thing with 1.12 at the moment is that dvander is currently refactoring the SourcePawn compiler completely, to the point that `int64` hypothetically may be introduced. I'm not sure if it will make sense to start 1.13 now.

Branching makes the most sense, because we can make breaking changes on the dev branch. This was suggested because `int64` on SP is a possibility. And when it is, we can destroy `MemoryPointer` without really breaking bcompat, because its dev branch.

2024-08-24 14:18 UTC, NotnHeavy commented
Ah, I supposed I haven't really thought about that. That makes more sense then.

2024-10-21 09:18 UTC, Kenzzer reviewed
Leaving a self-review; before I forget again what I was missing on this PR.
I plan on fixing all of this later this week.

2024-10-21 09:18 UTC, Kenzzer commented on extensions/sdktools/vdecoder.cpp
> +			Handle_t hndl = handlesys->CreateHandle(g_MemPtrHandle, new ForeignMemoryPointer(ptr), pContext->GetIdentity(), myself->GetIdentity(), &err);
Don't leak memory.

2024-10-21 09:18 UTC, Kenzzer commented on extensions/sdktools/vdecoder.cpp
> +				pContext->ThrowNativeError("Null/Invalid Handle MemoryPointer isn't allowed");
Remove "invalid", we can never branch here with an invalid handle. And it'd be weird to imply invalid handles can be used as "nullptr".

2024-10-21 09:18 UTC, Kenzzer commented on plugins/include/sourcemod.inc
> +};
Missing equal native; i.e if two MemoryPointer handles hold the same pointer value.

2024-10-30 19:43 UTC, NotnHeavy commented
[I decided to work on these for you](https://github.com/NotnHeavy/sourcemod/commit/7b1ae731f5c483cc268cc99e24e3d48740edf72e). My code should be fine, although I can't test on my laptop because both my laptop and internet are horrible in the place I am currently staying at.

2024-12-15 23:56 UTC, Kenzzer commented
Closing in favor of #2226 . The consensus internally seems to be that we avoid introducing a new handle type.

Will re-open if cited PR fails.

2024-12-15 23:56 UTC, closed without merging