Add new method - Converts a bit string to a string of flag characters
alliedmodders/sourcemod pull request #377
Opened 2015-08-19 21:13 UTC by s3bul

I wrote this method a long time ago, maybe this will be helpful.

2016-07-02 15:19 UTC, s3bul commented
I added new syntax, can someone look for that?

2021-03-08 11:06 UTC, peace-maker requested changes
Wow this is old. Sorry for the really long wait. The interchangeable bits vs AdminFlag vs character representation of admin permissions is ridiculous, but what we have I guess. Since we have natives for lots of the other conversions already this seems like a reasonable addition.

The function name could be a bit more descriptive. I'd suggest `FlagBitsToString`?

2021-04-21 09:42 UTC, s3bul commented
> `FlagBitsToString`

Yeah I add this very long time ago, but it's ok 😅 
Name `FlagBitsToString` is fine.

2021-05-20 23:32 UTC, KyleSanderson commented on plugins/include/admin.inc
> +	for (i = numId; i < maxSize; ++i)
flags[numFlags] = '\0';

2021-06-02 17:02 UTC, s3bul commented on plugins/include/admin.inc
> +	for (i = numId; i < maxSize; ++i)
Why `flags[numFlags] = '\0';`?
I think it should be `flags[numId] = '\0';` if `for` is too much

2021-06-17 11:43 UTC, peace-maker approved these changes
Thank you, this looks good now except for the usage of tabs for indentation in the doc comment, but this has waited for too long already. Sorry for taking this long and thank you for your patience!

2021-06-17 11:44 UTC, merged